# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vue CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: vite build
#    - run: npm test
    
    # Test current directory and change dist to kaso-agri
    - name: Test current directory
    - run: ls -la
    - run: pwd
    - run: mv ./dist ./kaso-agri
    
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./kaso-agri
        remote: ~/xindian_test/webui
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
